$(document).ready(function(){
    $('.search').click(function(){
        $('#pesquisa').css({
            visibility:'visible',
            width:'15vw',
            transition:'0.5s',
            opacity:'1',
        });
    });
});